project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - about.qmd
    - proyectos.qmd
    - publicaciones.qmd

website:
  favicon: ./images/favicon.png
  title: "Angel Merino | Portafolio de Proyectos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre Mí
      - href: proyectos.qmd
        text: Proyectos
      - href: publicaciones.qmd
        text: Publicaciones
    right:
      - icon: github
        href: https://github.com/anmerino-pnd
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/anmerino-pnd
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:acedeno00@gmail.com
        aria-label: Email

format:
  html:
    theme: 
      - flatly 
      - scustom.scss
    css: styles.css
    toc: false

lang: es