project:
  type: website
  output-dir: ../docs
  resources:
    - certificados/** 
  render:
    - index.qmd
    - about.qmd
    - proyectos.qmd
    - publicaciones.qmd
    - certificados.qmd        

website:
  favicon: ./images/favicon.png
  title: "Angel Merino | Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: proyectos.qmd
        text: Projects
      - href: publicaciones.qmd
        text: Publications
      - href: certificados.qmd   
        text: Certificates
    right:
      - icon: github
        href: https://github.com/anmerino-pnd
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com/in/anmerino-pnd
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:acedeno00@gmail.com
        aria-label: Email

format:
  html:
    theme: 
      - flatly 
      - scustom.scss
    css: styles.css
    toc: false

lang: en