---
title: "Arquitectura de datos: HFSQL a Data Lake"
format: 
    html:
         page-layout: article
toc: false
author: 
  - name: "Daniel Rivera Güémez"
  - name: "Arian García Milanes"
  - name: "Angel Merino Cedeño"
    email: "acedeno00@gmail.com"     # Aparece un icono de correo
    url: "https://www.linkedin.com/in/anmerino-pnd"          # Aparece icono de web si quieres
    affiliations:
        - name : "[📄 CV](https://docs.google.com/document/d/1bPJBc2WOGYZBIv6eyDXUrEm27WVeQLJP/edit?usp=sharing&ouid=113551267922364851191&rtpof=true&sd=true)"
date: last-modified
date-format: long
lang: es
---

# Resumen Ejecutivo

Este proyecto aborda uno de los desafíos más críticos en la industria actual: **la liberación de datos atrapados en sistemas heredados (Legacy Systems)**. 

El objetivo principal fue diseñar e implementar una arquitectura de datos capaz de extraer información transaccional masiva desde bases de datos **HFSQL (HyperFileSQL)**, transformar estos datos y cargarlos en un **Data Lake moderno**.

## El Desafío
La infraestructura existente dependía de controladores ODBC obsoletos que presentaban graves problemas de estabilidad (errores de segmentación y *stack smashing*) al ejecutarse en entornos de producción Linux modernos, impidiendo la automatización del análisis de datos.

## Mi rol
Como **ingeniero de datos**, diseñé la solución de bajo nivel, enfocándome en:

1.  **Estabilidad:** Aislar los procesos inestables mediante wrappers de Python.
2.  **Portabilidad:** Contenerizar la solución con **Podman** para garantizar la ejecución idéntica en desarrollo (Windows) y producción (Linux).
3.  **Rendimiento:** Optimizar la escritura de datos usando formatos columnares (Parquet).